### ISSUE TITLE
[Feature Request] Rapid charge?

### ISSUE THREAD

**Issue by CCF100** [teleshoes/tpacpi-bat#102]
My Lenovo Legion y540 supports a feature called "Rapid Charge" in the Lenovo Vantage software on Windows, which, as the name suggests, lets the battery charge significantly faster than normal... Could this project potentially support this, and if not, is there another project that would?

**Comment by teleshoes** [comment]
this particular ACPI interface is something that already exists, from lenovo. tpacpi-bat is merely communicating with it. (also thinkpads only, afail)
