### ISSUE TITLE
How can we test ?

### ISSUE THREAD

**Issue by Louson** [teleshoes/tpacpi-bat#107]
Hello. My laptop (t14 gen 2) is not in the supported list. What is the right way to test it's working ?
Can we add something in the README for that ?

**Comment by teleshoes** [comment]
in case you still care centuries later..
thanks for wanting to test! there is no straightforward testing procedure, and perhaps there should be. i might get out my old W520 and test it on there with an ultrabay battery, and document some results some day.

but if you DO test it and confirm that start/stop thresholds work for single or multi battery on new-ish thinkpads, thatd be nice to know! :)
