### ISSUE TITLE
Setting is applied to wrong bat

### ISSUE THREAD

**Issue by menzel** [teleshoes/tpacpi-bat#51]
When setting ST for bat 0 the ST for bat 1 is set. Same for SP.

(Thinkpad T430i, OS: Arch Linux)

[..@..] sudo tpacpi-bat -s ST 0 25
[..@..] sudo tpacpi-bat -g ST 0
Cannot specify 'either/both' for reading ST
[..@..] sudo tpacpi-bat -g ST 1
25 (relative percent)

**Comment by teleshoes** [comment]
sigh, you did not read the usage, but you are not alone. many people make this error, because lenovo's API uses annoying values. the batteries are one-indexed, not zero-indexed.
```
wolke:~$ tpacpi-bat -h
Usage:
...
    tpacpi-bat [-v] -s ST <bat{1,2,0}> <percent{0,1-99}>
    tpacpi-bat [-v] -s SP <bat{1,2,0}> <percent{0,1-99}>
...
    <bat>        1 for main, 2 for secondary, 0 for either/both
```
