### ISSUE TITLE
Force Charge

### ISSUE THREAD

**Issue by wasutton3** [teleshoes/tpacpi-bat#52]
Is there a way to force the system to charge? As in, the last discharge wasn't enough to drop below the threshold, but the next time I'll need it to be on battery, it won't have enough charge. Any solution? Similar to the charge-inhibit, but the exact opposite, a "force-charge" option (to the respective threshold at least).

**Comment by teleshoes** [comment]
just set the threshold and it will start charging, no?

**Comment by wasutton3** [comment]
It would, but then you have to fiddle with the threshold and make it change
back. maybe a toggle to set the start charge threshold to 0%? then an
interlock with the charge inhibit so it doesn't lose its mind.

On Sun, Mar 29, 2015 at 10:47 PM, Elliot Wolk <notifications@github.com>
wrote:

> just set the threshold and it will start charging, no?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/teleshoes/tpacpi-bat/issues/52#issuecomment-87521351>.
>



-- 
No trees were harmed in the sending of this message, but a rather large
number of electrons were terribly inconvenienced.

**Comment by teleshoes** [comment]
im not following you. this is what you want to do, right?
```
old=`tpacpi-bat -g ST 1`
tpacpi-bat -s ST 1 0
bat=0
while [ $bat -lt 100 ]; do
  now=`cat /sys/class/power_supply/BAT0/energy_now`
  full=`cat /sys/class/power_supply/BAT0/energy_full`
  bat=$((now * 100 / full));
  sleep 3600
done
tpacpi-bat -s ST 1 $old
```

to be clear, there is nothing in the thinkpad acpi interface for doing this directly. that being said, the api almost certainly exposes enough functionality for doing whatever it is that you want with a simple script

**Comment by linrunner** [comment]
The *only* way is to achieve this is to temporarily set the lower threshold above the charge level.

You may use [TLP](http://linrunner.de/en/tlp/docs/tlp-linux-advanced-power-management.html) to manage your thresholds (via tpacpi-bat of course). It has the command 

    tlp chargeonce

exactly for this use case.
