### ISSUE TITLE
Can't set the "min" variable on Thinkpad T430

### ISSUE THREAD

**Issue by write-your-own-os** [teleshoes/tpacpi-bat#61]
I'm running the command `sudo tpacpi-bat -s IC 0 1 65535`, but tpacpi-bat returns `invalid value for <min>`.

**Comment by teleshoes** [comment]
yea, very true. note that this is because of the error-handling for the BIC=>PSS bit-shift bug. ill test 65535 and 65535*2=131070 to see what they do soon.

in other news, i think you probably just want to do ```sudo tpacpi-bat -s IC 0 1```

**Comment by teleshoes** [comment]
hmm, yea, i think what ill do is just allow 65535 without multiplying by 2 as a special case. this may just inhibit charge for 32767 min, or it may do it forever.

**Comment by teleshoes** [comment]
done
