### ISSUE TITLE
Error: AE_NOT_FOUND

### ISSUE THREAD

**Issue by teresaejunior** [teleshoes/tpacpi-bat#66]
I have a Lenovo G40-80, and while searching for a method to control the maximum charge threshold for my battery, I have found [this thread](http://unix.stackexchange.com/questions/234809/laptop-battery-doesnt-raise-from-59-ie-showing-wrong-battery-stats) showing how to install tpacpi-bat. I currently get this error:

    Error: AE_NOT_FOUND for ASL base: \_SB.PCI0.LPCB.EC0.HKEY
    Error: AE_NOT_FOUND at ./tpacpi-bat line 409.

The file /sys/class/power_supply/BAT0/device/path has a value of `\_SB_.PCI0.LPCB.EC0_.BAT0`.

The idea is to use the default maximum of 59% while I'm at home to preserve the battery, and then charge it to 100% when I need to go out with my laptop.

Thank you for your attention!

**Comment by teleshoes** [comment]
that is the error you would get if your laptop doesnt have this interface. ive never seen a non-thinkpad laptop with this interface, so thats probably the case (and if it is, nothing you can do will make it work).
if you wish to continue investigating, check out other issues for unsupported models (e.g.: issue #4)
good luck!
