### ISSUE TITLE
Thresholds not considered if laptop is switched off ... 

### ISSUE THREAD

**Issue by the-drunk-coder** [teleshoes/tpacpi-bat#74]
Hi,

i've been using tpacpi-bat on my T440s for a while now, but it seems that it only works if the computer 
is switched on.

I remember that the thresholds were considered even when the computer was off a while ago. 
Has anything changed, or is it just my memory that is blurry ?

Regards

**Comment by teleshoes** [comment]
no, im fairly certain stop threshold worked in the past for my W520 while its off. (perhaps you use a service that removes the thresholds when its down-ed?)
either way, thats entirely up to the BIOS, nothing tpacpi-bat could possibly do about it
