### ISSUE TITLE
Draw power from USB-C Power Bank?

### ISSUE THREAD

**Issue by cbm** [teleshoes/tpacpi-bat#78]
I just got a X1 Carbon gen 5 and I tested a RavPower bank that supports 20V1.5A over usb-c.

Setting the charging limits with tpacpi-bat works.

The laptop charges from the bank on standby and power-off. However, during power-on the
external battery is ignored. Is there any hints on checking if we can get any power from the
bank by playing around with the charging controller?

Any hints on where to look will be highly appreciated. I am also willing to collaborate in
developing/debugging such an approach, just need a starting point.

**Comment by teleshoes** [comment]
mm, a noble endeavour. im afraid i cant be of assistance personally, but good luck!
