### ISSUE TITLE
acpi_call requires kernel sources

### ISSUE THREAD

**Issue by Raffaello** [teleshoes/tpacpi-bat#80]
It would be nice to add the info in the readme or auto install the kernel sources automatically from `install.pl`

**Comment by teleshoes** [comment]
acpi_call is listed as a requirement in the README. that means, by definition, any dependency for acpi_call is also a dependency for tpacpi-bat.

as for `install.pl`, its fairly distribution-agnostic, while installing linux sources is distribution-dependent, so it cant install the sources for you.

`install.pl` is a somewhat useful tool, but mostly its just to illustrate how it expects acpi_call and tpacpi-bat to be installed.
