### ISSUE TITLE
Installation fails in due to implicit function declaration error

### ISSUE THREAD

**Issue by bgx90** [teleshoes/tpacpi-bat#88]
The make step of install.pl fails due to the implicit declaration error cause by acpi_call.c
```
make
make -C /lib/modules/4.13.0-1-amd64/build M=/tmp/acpi_call modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-1-amd64'
CC [M]  /tmp/acpi_call/acpi_call.o
/tmp/acpi_call/acpi_call.c: In function ‘acpi_proc_write’:
/tmp/acpi_call/acpi_call.c:307:9: error: implicit declaration of function ‘copy_from_user’ [-Werror=implicit-function-declaration]
if (copy_from_user( input, buff, len )) {
```
The result is that the code is not compiled so the module cannot be loaded.

The solution is to add the following include directive to acpi_call.c
`#include <linux/uaccess.h>`

After I added that include directive, the code compiled successfully and install.pl completed successfully.

gcc version 7.2.0 (Debian 7.2.0-8) 
Operating System: Debian GNU/Linux buster/sid
Kernel: Linux 4.13.0-1-amd64
Architecture: x86-64

**Comment by teleshoes** [comment]
(fixed 3 years ago by cefn)
